const cards = [
    {
        id: 1,
        title: "Find Something",
        pic: "images/cat3.jpeg",
        alt: "cat looks at the front",
        text: "Cat Craze: The feline phenomenon has taken the world by storm, with cats reigning supreme as beloved companions in households worldwide.",
        button: "true",
        category:"Brown",
    },
    {
        id: 2,
        title: "Magic mirror",
        pic: "images/cat4.jpeg",
        alt: "cat at the mirror",
        text: "Internet Sensation: Cats have become an internet sensation, capturing hearts through viral videos and memes, showcasing their quirky behaviors and endearing personalities. ",
        button: "false",
        category:"Brown and yellow",
    },
    {
        id: 3,
        title: "Nice Dream",
        pic: "images/cat5.jpeg",
        alt: "sleeping cat",
        text: "Cultural Icons: From ancient Egyptian deities to modern pop culture, cats have left an indelible mark, becoming symbols of mystery, independence, and charm.",
        button: "true",
        category:"White and grey",
    },
    {
        id: 4,
        title: "shock",
        pic: "images/cat6.jpeg",
        alt: "cat is verk shocked",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds, each with its unique characteristics, from the regal Maine Coon to the sleek Siamese.",
        button: "true",
        category:"White and grey",
    },
    {
        id: 5,
        title: "Thinking",
        pic: "images/cat7.jpeg",
        alt: "cat is thinking",
        text: "Mysterious Behaviors: The enigmatic behaviors of cats, such a contribute to their mystique, keeping owners endlessly intrigued.",
        button: "true",
        category:"Brown and yellow",
    },
    {
        id: 6,
        title: "Traveling",
        pic: "images/cat8.jpeg",
        alt: "white cat in a blue sky",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds.",
        button: "false",
        category:"White",
    },
    {
        id: 7,
        title: "New gloves",
        pic: "images/cat9.jpeg",
        alt: "cat in red background",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds.",
        button: "false",
        category:"Brown and white",
    },
    {
        id: 8,
        title: "Twins of the last cats",
        pic: "images/cat10.jpeg",
        alt: "Cat stands in a corner",
        text: "Mysterious Behaviors: The enigmatic behaviors of cats, such as kneading, pupose, contribute to their mystique, keeping owners endlessly intrigued.",
        button: "false",
        category:"Brown",
    },
    {
        id: 9,
        title: "Got tired",
        pic: "images/cat11.jpeg",
        alt: "cat with a ball",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds.",
        category:"Brown and yellow",
    },
    {
        id: 10,
        title: "Selfie",
        pic: "images/cat12.jpeg",
        alt: "cat in a wooden background",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds.",
        category:"Brown and yellow",
    },
    {
        id: 11,
        title: "Sherlock Holmes",
        pic: "images/cat13.jpeg",
        alt: "cat is finding something",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds.",
        button: "false",
        category:"Brown and yellow",
    },
    {
        id: 12,
        title: "I got you",
        pic: "images/cat14.jpeg",
        alt: "cat in a hand",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds.",
        button: "false",
        category:"Brown and yellow",
    },
];

export default cards;