const cards = [
    {
        id: 1,
        title: "Find Something",
        pic: "http://placekitten.com/200/200?image=13",
        alt: "cat looks at the front",
        text: "Cat Craze: The feline phenomenon has taken the world by storm, with cats reigning supreme as beloved companions in households worldwide.",
        button: "true",
    },
    {
        id: 2,
        title: "Magic mirror",
        pic: "http://placekitten.com/200/200?image=14",
        alt: "cat at the mirror",
        text: "Internet Sensation: Cats have become an internet sensation, capturing hearts through viral videos and memes, showcasing their quirky behaviors and endearing personalities. ",
        button: "false",
    },
    {
        id: 3,
        title: "Nice Dream",
        pic: "http://placekitten.com/200/200?image=15",
        alt: "sleeping cat",
        text: "Cultural Icons: From ancient Egyptian deities to modern pop culture, cats have left an indelible mark, becoming symbols of mystery, independence, and charm.",
        button: "true",
    },
    {
        id: 4,
        title: "shock",
        pic: "http://placekitten.com/200/200?image=16",
        alt: "cat is verk shocked",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds, each with its unique characteristics, from the regal Maine Coon to the sleek Siamese.",
        button: "true",
    },
    {
        id: 5,
        title: "Thinking",
        pic: "http://placekitten.com/200/200?image=12",
        alt: "cat is thinking",
        text: "Mysterious Behaviors: The enigmatic behaviors of cats, such a contribute to their mystique, keeping owners endlessly intrigued.",
        button: "true",
    },
    {
        id: 6,
        title: "Traveling",
        pic: "http://placekitten.com/200/200?image=11",
        alt: "white cat in a blue sky",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds.",
        button: "false",
    },
    {
        id: 7,
        title: "New gloves",
        pic: "http://placekitten.com/200/200?image=10",
        alt: "cat in red background",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds.",
        button: "false",
    },
    {
        id: 8,
        title: "Twins of the last cats",
        pic: "http://placekitten.com/200/200?image=9",
        alt: "Cat stands in a corner",
        text: "Mysterious Behaviors: The enigmatic behaviors of cats, such as kneading, pupose, contribute to their mystique, keeping owners endlessly intrigued.",
        button: "false",
    },
    {
        id: 9,
        title: "Got tired",
        pic: "http://placekitten.com/200/200?image=8",
        alt: "cat with a ball",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds.",
    },
    {
        id: 10,
        title: "Selfie",
        pic: "http://placekitten.com/200/200?image=7",
        alt: "cat in a wooden background",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds.",
    },
    {
        id: 11,
        title: "Sherlock Holmes",
        pic: "http://placekitten.com/200/200?image=6",
        alt: "cat is finding something",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds.",
        button: "false",
    },
    {
        id: 12,
        title: "I got you",
        pic: "http://placekitten.com/200/200?image=5",
        alt: "cat in a hand",
        text: "Diverse Breeds: The feline world boasts a diverse array of breeds.",
        button: "false",
    },
];

export default cards;